import type { StaticImageData } from "next/image";
import Head from "next/head";
import { compiler } from "markdown-to-jsx";
import favicon from "public/favicon.svg";
import styles from "./index.module.css";
import React from "react";
import gaytips from "public/gaytips.md";

export default function Home() {
	function isString<T>(value: T): value is T extends string ? T : never {
		return typeof value === "string";
	}

	function createElement(
		type: string | React.FunctionComponent | React.ComponentClass,
		elementProps: JSX.IntrinsicAttributes,
		...children: React.ReactNode[]
	) {
		const props = elementProps as typeof elementProps & { id?: string };
		const headingTypes = ["h1", "h2", "h3", "h4", "h5", "h6"];
		const isH = isString(type) && type.startsWith("h") && headingTypes.includes(type);
		if (isH && props.id !== undefined) {
			return (
				<a href={`#${props.id}`} key={props.key}>
					{React.createElement(type, { ...props, key: undefined }, ...children)}
				</a>
			);
		}
		return React.createElement(type, props, ...children);
	}

	return (
		<>
			<Head>
				<title>gay tips (totally from professionals)</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href={(favicon as StaticImageData).src} />
			</Head>
			<main className={styles.main}>
				<div className={styles.container}>{compiler(gaytips, { createElement })}</div>
			</main>
		</>
	);
}

